blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/Yash159357/BREVITY/discussions
    about: Ask questions and discuss ideas with the community
  - name: 💡 Feature Ideas
    url: https://discord.gg/nVKvVqWEwX
    about: Share and discuss feature ideas before creating formal requests
