name: 📚 Documentation Update
description: Suggest improvements to documentation
title: "[DOCS] - "
labels: ["documentation", "enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve our documentation! Clear documentation helps everyone contribute to and use Brevity effectively.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please check the following before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have reviewed the current documentation
          required: true

  - type: dropdown
    id: documentation-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs updating?
      options:
        - README - Main project README file
        - API Documentation - REST API or GraphQL documentation
        - Setup Guide - Installation and setup instructions
        - Contributing Guide - Guidelines for contributors
        - User Guide - How to use the app features
        - Developer Guide - Technical documentation for developers
        - Code Comments - Inline code documentation
        - Architecture - System design and architecture docs
        - Troubleshooting - Common issues and solutions
        - Changelog - Release notes and version history
        - Other
    validations:
      required: true

  - type: textarea
    id: current-issue
    attributes:
      label: Current Issue
      description: What's wrong with the current documentation?
      placeholder: |
        Describe the problem:
        - Missing information
        - Outdated content
        - Unclear explanations
        - Incorrect instructions
        - Poor organization
    validations:
      required: true

  - type: textarea
    id: proposed-improvement
    attributes:
      label: Proposed Improvement
      description: How should the documentation be improved?
      placeholder: Describe what changes should be made to improve the documentation...
    validations:
      required: true

  - type: textarea
    id: specific-sections
    attributes:
      label: Specific Sections/Files
      description: Which specific files, sections, or pages need updating?
      placeholder: |
        List specific locations:
        - File: README.md, Section: Installation
        - File: docs/api.md, Section: Authentication
        - Inline comments in: src/components/Header.js

  - type: dropdown
    id: target-audience
    attributes:
      label: Target Audience
      description: Who is the primary audience for this documentation?
      options:
        - End Users - People using the app
        - New Contributors - First-time contributors
        - Experienced Developers - Seasoned contributors
        - Project Maintainers - Core team members
        - System Administrators - Deployment and operations
        - All audiences
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this documentation update?
      options:
        - Low - Minor improvement
        - Medium - Would help users/contributors
        - High - Important for project success
        - Critical - Blocking users/contributors
    validations:
      required: true

  - type: textarea
    id: content-suggestion
    attributes:
      label: Content Suggestion
      description: If you have specific content to add or modify, include it here
      placeholder: |
        Provide the actual content you'd like to see:
        
        ```markdown
        ## Your suggested content here
        ```

  - type: textarea
    id: examples-references
    attributes:
      label: Examples/References
      description: Provide examples or references for good documentation
      placeholder: |
        Include:
        - Links to similar projects with good docs
        - Examples of what good documentation looks like
        - Screenshots of confusing sections

  - type: textarea
    id: user-feedback
    attributes:
      label: User Feedback
      description: Have you received feedback from others about this documentation issue?
      placeholder: Share any feedback from users or contributors about the documentation...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Include any other details, screenshots, or context that would help improve the documentation...
