name: ✨ New Feature Request
description: Suggest a new feature for the app
title: "[FEATURE] - "
labels: ["enhancement", "feature-request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide detailed information about your request.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please check the following before submitting
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: This feature doesn't already exist in the app
          required: true
        - label: This feature aligns with the app's purpose and goals
          required: true

  - type: textarea
    id: feature-summary
    attributes:
      label: Feature Summary
      description: A brief, clear summary of the feature you're requesting
      placeholder: Summarize the feature in one or two sentences...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What need does it address?
      placeholder: Describe the problem or need this feature would address...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: Explain how you envision this feature working...
    validations:
      required: true

  - type: textarea
    id: user-stories
    attributes:
      label: User Stories
      description: Describe how users would interact with this feature
      placeholder: |
        As a [type of user], I want [goal] so that [benefit].
        
        Example scenarios:
        - When I...
        - I should be able to...
        - The system should...
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: Which category best describes this feature?
      options:
        - Core Functionality - Main app features
        - User Management - Profile, settings, authentication
        - Content Creation - Text editing, formatting
        - Sharing & Export - Sharing content, export options
        - Personalization - Themes, preferences, customization
        - Accessibility - Features for users with disabilities
        - Integration - Third-party services, APIs
        - Analytics & Insights - Data tracking, reporting
        - Security - Privacy, data protection
        - Other
    validations:
      required: true

  - type: dropdown
    id: target-platforms
    attributes:
      label: Target Platforms
      description: Which platforms should this feature be available on?
      multiple: true
      options:
        - Android
        - iOS
        - Web
        - All platforms

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives Considered
      description: What alternative solutions have you considered?
      placeholder: Describe any alternative approaches you've thought about...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be useful
        - High - Important for my use case
        - Critical - Essential for app success
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What conditions must be met for this feature to be considered complete?
      placeholder: |
        Define what "done" looks like:
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, mockups, or examples
      placeholder: Provide any additional information, references, or examples...
