name: ⚡ Performance Optimization
description: Report performance issues or suggest optimizations
title: "[PERFORMANCE] - "
labels: ["performance", "optimization", "needs-investigation"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve Brevity's performance! Please provide detailed information about the performance issue or optimization opportunity.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please check the following before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have tested on multiple devices/environments if possible
          required: true
        - label: I have verified this is a performance issue, not a bug
          required: true

  - type: dropdown
    id: performance-category
    attributes:
      label: Performance Category
      description: What type of performance issue is this?
      options:
        - App Startup - Slow app launch or initialization
        - UI Responsiveness - Laggy interactions, slow animations
        - Memory Usage - High memory consumption, memory leaks
        - Battery Drain - Excessive battery usage
        - Network Performance - Slow API calls, inefficient requests
        - Database Performance - Slow queries, inefficient data access
        - Rendering Performance - Slow screen rendering, frame drops
        - Bundle Size - Large app size, inefficient builds
        - Background Processing - Inefficient background tasks
        - Other
    validations:
      required: true

  - type: textarea
    id: performance-issue
    attributes:
      label: Performance Issue Description
      description: Describe the performance problem in detail
      placeholder: Explain what performance issue you're experiencing...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this performance issue?
      placeholder: |
        1. Open the app
        2. Navigate to...
        3. Perform action...
        4. Notice performance issue
    validations:
      required: true

  - type: textarea
    id: performance-metrics
    attributes:
      label: Performance Metrics
      description: Provide specific measurements if available
      placeholder: |
        Include any measurable data:
        - Load time: X seconds
        - Memory usage: X MB
        - CPU usage: X%
        - Battery drain: X% per hour
        - Frame rate: X fps
        - Network requests: X requests taking X seconds

  - type: dropdown
    id: affected-platforms
    attributes:
      label: Affected Platforms
      description: Which platforms experience this performance issue?
      multiple: true
      options:
        - Android
        - iOS
        - Web
        - All platforms
    validations:
      required: true

  - type: textarea
    id: device-specifications
    attributes:
      label: Device Specifications
      description: Provide details about the device(s) where you noticed the issue
      placeholder: |
        Device information:
        - Device model: 
        - OS version: 
        - RAM: 
        - Storage: 
        - Network connection: 
        - App version:
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this performance issue?
      options:
        - Low - Minor slowdown, barely noticeable
        - Medium - Noticeable delay affecting user experience
        - High - Significant performance impact
        - Critical - App unusable due to performance issues
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: If you have ideas for optimization, describe them here
      placeholder: Suggest potential optimizations or solutions...

  - type: textarea
    id: profiling-data
    attributes:
      label: Profiling Data
      description: Share any profiling data, screenshots, or performance analysis
      placeholder: Attach performance profiles, screenshots, or analysis data

  - type: textarea
    id: workarounds
    attributes:
      label: Current Workarounds
      description: Are there any workarounds that help with the performance issue?
      placeholder: Describe any temporary solutions or workarounds...

  - type: textarea
    id: user-impact
    attributes:
      label: User Impact
      description: How does this performance issue affect users?
      placeholder: Describe the impact on user experience and app usage...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information about the performance issue
      placeholder: Include logs, crash reports, or other technical details...
